company: Yaskawa Europe GmbH
author: deGroot
name: Library Aaaa
description: |
  This library is (add some more text here).
  - some `markdown` *here*.
comment: Some short description here
releases:
  - version: 2.3.4
    date: 2020-12-16
    author: John Doe
    assets:
      - name: S7-1500
        # url: "www.example.com/siemens/4"
        date: 2021-03-04
      - name: Beckhoff
        url: "www.example.com/beckhoff/10"
        date: 2021-03-11
    added:
      - "`AddNumbers`"
      - "`MyOpenSourceFunction`"
  - version: 2.3.3
    date: 2020-10-31
    author: deGroot
    assets:
      - name: S7-1500
        url: "www.example.com/siemens/3"
        date: 2020-10-22
      - name: Beckhoff
        url: "www.example.com/beckhoff/9"
        date: 2021-10-20
    added:
      - "`Bratwurst`"