[build]
command = "hugo -e production -s exampleSite -t repo --themesDir=../.. --minify --gc --baseURL https://plc-docs-theme.netlify.app"

[build.environment]
HUGO_VERSION = "0.81.0"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"