name = "PLC Docs Theme"
license = "MIT"
licenselink = "https://github.com/mrBrutus/hugo-plc-docs-theme/blob/main/LICENSE"
description = "A Hugo theme for creating a PLC documentation website using a docs-as-code approach."
homepage = "http://example.com/"
tags = ["plc", "programmable logic controller", "docs", "documentation", "docs-as-code", "responsive", "tailwindcss", "structured text", "ST", "IEC61131"]
features = ["Highlight.js", "light/dark mode"]
min_version = "0.81.0"

[author]
  name = "Bertus de Groot"
  homepage = ""
